In [28]:
import pandas as pd #for data cleaning
import numpy as np #for linear algebra
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
#loading the "movies.csv" file as a variable called "movies"
movies = pd.read_csv("movies.csv")

C:\Users\Youssef Atef\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [30]:
#pritning the columns of the dataframe
movies.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'avg_vote', 'votes',
       'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore',
       'reviews_from_users', 'reviews_from_critics'],
      dtype='object')

In [31]:
#Making a function that takes a dataset as a parameter and store a specific values of each row as a string and store these
#strings in a list and then return that list
def features(data):
    important_features = []
    for i in range(0,movies.shape[0]):
        important_features.append(data['title'][i] +' '+ data['genre'][i]+' ' + str(data["director"][i]) + " " + str(data["country"][i]) + " " + str(data["language"][i]) + " " + str(data["writer"][i])+ " " + str(data["actors"][i])+ " " + str(data["description"][i]))
    return important_features

In [32]:
#calling the function and storing it in a new column
movies['important_feature'] = features(movies)

In [33]:
#printing the column
movies['important_feature']

0        Miss Jerry Romance Alexander Black USA None Al...
1        The Story of the Kelly Gang Biography, Crime, ...
2        Den sorte drøm Drama Urban Gad Germany, Denmar...
3        Cleopatra Drama, History Charles L. Gaskill US...
4        L'Inferno Adventure, Drama, Fantasy Francesco ...
                               ...                        
85850    Le lion Comedy Ludovic Colbeau-Justin France, ...
85851    De Beentjes van Sint-Hildegard Comedy, Drama J...
85852    Padmavyuhathile Abhimanyu Drama Vineesh Aarady...
85853    Sokagin Çocuklari Drama, Family Ahmet Faik Aki...
85854    La vida sense la Sara Amat Drama Laura Jou Spa...
Name: important_feature, Length: 85855, dtype: object

In [34]:
movies.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'avg_vote', 'votes',
       'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore',
       'reviews_from_users', 'reviews_from_critics', 'important_feature'],
      dtype='object')

In [35]:
#checking for null values
movies.isnull().any()

imdb_title_id            False
title                    False
original_title           False
year                     False
date_published           False
genre                    False
duration                 False
country                   True
language                  True
director                  True
writer                    True
production_company        True
actors                    True
description               True
avg_vote                 False
votes                    False
budget                    True
usa_gross_income          True
worlwide_gross_income     True
metascore                 True
reviews_from_users        True
reviews_from_critics      True
important_feature        False
dtype: bool

In [36]:
#dropping the null values
movies = movies.dropna()

In [37]:
#re-sorting the dataframe in an descending order of date published
movies = movies.sort_values('date_published', ascending = False)

In [38]:
#slicing the first 10,000 rows of the datafarme
movies = movies.head(10000)

In [39]:
#printing the first 3 rows of the dataframe
movies.head(3)

imdb_title_id                title   original_title  year  \
52318    tt10059518  Il giorno sbagliato         Unhinged  2020   
80369     tt6348138          Mister Link     Missing Link  2019   
75419     tt4682266          New Mutants  The New Mutants  2020   

      date_published                         genre  duration      country  \
52318     2020-09-24              Action, Thriller        90          USA   
80369     2020-09-17  Animation, Adventure, Comedy        93  Canada, USA   
75419     2020-09-02        Action, Horror, Sci-Fi        94  USA, Canada   

                        language       director  ...  \
52318                    English  Derrick Borte  ...   
80369  English, Spanish, Tibetan   Chris Butler  ...   
75419                    English     Josh Boone  ...   

                                             description avg_vote  votes  \
52318  After a confrontation with an unstable man at ...      6.2   4720   
80369  Mr. Link recruits explorer Sir Lionel Frost to...      6.7  20080   
75419  Five young mutants, just discovering their abi...      5.6   4621   

            budget  usa_gross_income  worlwide_gross_income metascore  \
52318   $ 33000000         $ 9025406             $ 21025406      40.0   
80369  $ 100000000        $ 16649539             $ 26249469      68.0   
75419   $ 67000000         $ 7487310             $ 10387310      41.0   

      reviews_from_users reviews_from_critics  \
52318              159.0                119.0   
80369              173.0                152.0   
75419              173.0                 54.0   

                                       important_feature  
52318  Il giorno sbagliato Action, Thriller Derrick B...  
80369  Mister Link Animation, Adventure, Comedy Chris...  
75419  New Mutants Action, Horror, Sci-Fi Josh Boone ...  

[3 rows x 23 columns]

In [40]:
#fitting the important features column into the countVectorizer
cm = CountVectorizer().fit_transform(movies['important_feature'])

In [41]:
#making a matric token of the CountVectorizer
cs = cosine_similarity(cm)
print(cs)

[[1.         0.11700158 0.04294488 ... 0.10562504 0.09248297 0.09810967]
 [0.11700158 1.         0.12487107 ... 0.19145551 0.1955733  0.19450505]
 [0.04294488 0.12487107 1.         ... 0.07905694 0.08075729 0.09637941]
 ...
 [0.10562504 0.19145551 0.07905694 ... 1.         0.52494153 0.19189755]
 [0.09248297 0.1955733  0.08075729 ... 0.52494153 1.         0.18449398]
 [0.09810967 0.19450505 0.09637941 ... 0.19189755 0.18449398 1.        ]]


In [42]:
#printng the sahpe of the matric
cs.shape

(6616, 6616)

In [43]:
#resetting the index of the dataframe
movies = movies.reset_index(drop=True)

In [44]:
#craeting a new ID column and store the index values in it
movies["ID"] = movies.index

In [45]:
#printing the first 3 rows of the dataframe
movies.head(3)

imdb_title_id                title   original_title  year date_published  \
0    tt10059518  Il giorno sbagliato         Unhinged  2020     2020-09-24   
1     tt6348138          Mister Link     Missing Link  2019     2020-09-17   
2     tt4682266          New Mutants  The New Mutants  2020     2020-09-02   

                          genre  duration      country  \
0              Action, Thriller        90          USA   
1  Animation, Adventure, Comedy        93  Canada, USA   
2        Action, Horror, Sci-Fi        94  USA, Canada   

                    language       director  ... avg_vote  votes       budget  \
0                    English  Derrick Borte  ...      6.2   4720   $ 33000000   
1  English, Spanish, Tibetan   Chris Butler  ...      6.7  20080  $ 100000000   
2                    English     Josh Boone  ...      5.6   4621   $ 67000000   

  usa_gross_income  worlwide_gross_income  metascore reviews_from_users  \
0        $ 9025406             $ 21025406       40.0              159.0   
1       $ 16649539             $ 26249469       68.0              173.0   
2        $ 7487310             $ 10387310       41.0              173.0   

  reviews_from_critics                                  important_feature  ID  
0                119.0  Il giorno sbagliato Action, Thriller Derrick B...   0  
1                152.0  Mister Link Animation, Adventure, Comedy Chris...   1  
2                 54.0  New Mutants Action, Horror, Sci-Fi Josh Boone ...   2  

[3 rows x 24 columns]

In [46]:
#getting the ID of a movie
title = 'Fight Club'
movie_id = movies[movies.title == title]["ID"].values[0]
movie_id

4844

In [47]:
#making a dictionary of this movie and the degree of similarity with the other movies 
scores = list(enumerate(cs[movie_id]))

In [48]:
#storing the score as a list of tubles of movie ID and its score, and then removing the first value since it's the movie score 
#with itself which will always be 1
sorted_scores = sorted(scores, key = lambda x:x[1], reverse = True)
sorted_scores = sorted_scores[1:]

In [49]:
sorted_scores[:10]

[(5154, 0.21341639745917707),
 (986, 0.2056531864151556),
 (1590, 0.19978980551207964),
 (6234, 0.1866272256725398),
 (5749, 0.1818335167131459),
 (6157, 0.17746819660511284),
 (3748, 0.17734310717834892),
 (3216, 0.17697315028813224),
 (3189, 0.1757398728916594),
 (4960, 0.17453202440084273)]

In [50]:
#Testing the model by making a for loop to return the most similar 10 movies to the ID we passed
j = 0
print("The 10 most recommended movies to",title,"are:\n")
for item in sorted_scores:
    movie_title = movies[movies["ID"] == item[0]]['title'].values[0]
    print(str(j+1) + "- "+ movie_title)
    j += 1
    if j>9:
        break

The 10 most recommended movies to Fight Club are:

1- L'ombra del diavolo
2- Fury
3- Cloud Atlas
4- Rambo
5- L'ultima battuta
6- Top Secret!
7- A Dirty Shame
8- Scoop
9- Uomini & donne - Tutti dovrebbero venire... almeno una volta!
10- Il prigioniero


In [51]:
#Making a function that recommend movies
def Recommend(movie):
    movie_id = movies[movies.title == movie]["ID"].values[0]
    scores = list(enumerate(cs[movie_id]))
    sorted_scores = sorted(scores, key = lambda x:x[1], reverse = True)
    sorted_scores = sorted_scores[1:]
    j = 0
    print("The 10 most recommended movies to",movie,"are:\n")
    for item in sorted_scores:
        movie_title = movies[movies["ID"] == item[0]]['title'].values[0]
        print(str(j+1) + "- "+ movie_title)
        j += 1
        if j>9:
            break

In [52]:
#making a function 
def check(title_):
    lower = movies.title.str.lower()
    return movies[lower.str.contains(title_)].title.values[0]
    

In [57]:
Recommend('The Amazing Spider-Man')

The 10 most recommended movies to The Amazing Spider-Man are:

1- The Amazing Spider-Man 2 - Il potere di Electro
2- Sinbad - La leggenda dei sette mari
3- Spider-Man
4- Le crociate - Kingdom of Heaven
5- Shooter
6- Resident Evil: Apocalypse
7- Flash Gordon
8- Spider-Man: Homecoming
9- The Last Stand - L'ultima sfida
10- Victor: La storia segreta del dottor Frankenstein
